modelname   : RiverTown
modelcomment: >
    NetLogo Model used as an engineering water management exercise
baseurl     : /RiverTown
accountname : VicCastillo
preurl      : https://github.com/VicCastillo
#
gems:
  - jekyll-sitemap
markdown: redcarpet
exclude:  ['NIL']
encoding: UTF-8

