modelname   : RiverTown
modelcomment: >
    Template for model pages. 
baseurl     : /RiverTown
accountname : VicCastillo
preurl      : https://github.com/VicCastillo
#
gems:
  - jekyll-sitemap
markdown: redcarpet
exclude:  ['NIL']
encoding: UTF-8

